### ISSUE TITLE
scrat server start  报错

### ISSUE THREAD

**Issue by djxhero** [scrat-team/scrat#5]
scrat sever clean ,然后 scrat server start  报错了：
dudeMacBook-Pro:public_html du$ scrat server start
 ➜ server is running

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/du/.scrat-tmp/www'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by JohnTian** [comment]
thanks @fouber good job.
